modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
modId="archaicraft"
version="0.0.1-1.19"
displayName="Archaicraft"
logoFile="archaicraft.png"
credits=""
authors="IsCactus"
description='''
A mod for aspiring alchemists.
'''

[[dependencies.archaicraft]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.archaicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
